package com.healthmanagement.SecurityConfig.entity;

public enum Speciality {
    SURGICAL_SPECIALTIE,
    INTERNAL_MEDICINE_SPECIALTIES,
    PEDIATRICS_AND_CHILD_HEALTH_SPECIALTIES,
    WOMENS_HEALTH_SPECIALTIES,
    CANCER_AND_ONCOLOGY_SPECIALTIES,
    NEUROLOGY_AND_PSYCHIATRY_SPECIALTIES,
    EMERGENCY_MEDICINE_AND_CRITICAL_CARE_SPECIALTIES,
    DIAGNOSTIC_AND_IMAGING_SPECIALTIES,
    ANESTHESIA_AND_PAIN_MANAGEMENT_SPECIALTIES,
    ALLERGY_AND_IMMUNOLOGY_SPECIALTIES

}
