package com.example.appointmentservice.entity;

public enum MedicalEquipment {
    STETHOSCOPE,
    BLOOD_PRESSURE_MONITOR,
    THERMOMETER,
    OTOSCOPE,
    OPHTHALMOSCOPE,
    ECG_MACHINE,
    X_RAY_MACHINE,
    ULTRASOUND_MACHINE,
    MRI_MACHINE,
    DEFIBRILLATOR,
    VENTILATOR,
    INFUSION_PUMP,
    SURGICAL_INSTRUMENTS,
    DOPPLER_ULTRASOUND,
    PULSE_OXIMETER,
    NEBULIZER,
    C_ARM,
    BLOOD_GLUCOSE_METER,
    WHEELCHAIR,
    CRUTCHES,
    HOSPITAL_BED,
    INCUBATOR,
    PACEMAKER,
    COLPOSCOPE,
    HOLTER_MONITOR
}
